spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloSpring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tldjs0309@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  base64Secret: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="

#    database-platform: